//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetParameterCS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamAngleX,-30,30")]
        public string ID_1 {
            get {
                return ((string)(this["ID_1"]));
            }
            set {
                this["ID_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamAngleY,-30,30")]
        public string ID_2 {
            get {
                return ((string)(this["ID_2"]));
            }
            set {
                this["ID_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamAngleZ,-30,30")]
        public string ID_3 {
            get {
                return ((string)(this["ID_3"]));
            }
            set {
                this["ID_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamEyeLOpen,0,1")]
        public string ID_4 {
            get {
                return ((string)(this["ID_4"]));
            }
            set {
                this["ID_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamEyeLSmile,0,1")]
        public string ID_5 {
            get {
                return ((string)(this["ID_5"]));
            }
            set {
                this["ID_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamEyeROpen,0,1")]
        public string ID_6 {
            get {
                return ((string)(this["ID_6"]));
            }
            set {
                this["ID_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamEyeRSmile,0,1")]
        public string ID_7 {
            get {
                return ((string)(this["ID_7"]));
            }
            set {
                this["ID_7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamEyeBallX,-1,1")]
        public string ID_8 {
            get {
                return ((string)(this["ID_8"]));
            }
            set {
                this["ID_8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamEyeBallY,-1,1")]
        public string ID_9 {
            get {
                return ((string)(this["ID_9"]));
            }
            set {
                this["ID_9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamEyeBallForm,-1,1")]
        public string ID_10 {
            get {
                return ((string)(this["ID_10"]));
            }
            set {
                this["ID_10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamBrowLY,-1,1")]
        public string ID_11 {
            get {
                return ((string)(this["ID_11"]));
            }
            set {
                this["ID_11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamBrowRY,-1,1")]
        public string ID_12 {
            get {
                return ((string)(this["ID_12"]));
            }
            set {
                this["ID_12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamBrowLX,-1,1")]
        public string ID_13 {
            get {
                return ((string)(this["ID_13"]));
            }
            set {
                this["ID_13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamBrowRX,-1,1")]
        public string ID_14 {
            get {
                return ((string)(this["ID_14"]));
            }
            set {
                this["ID_14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamBrowLAngle,-1,1")]
        public string ID_15 {
            get {
                return ((string)(this["ID_15"]));
            }
            set {
                this["ID_15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamBrowRAngle,-1,1")]
        public string ID_16 {
            get {
                return ((string)(this["ID_16"]));
            }
            set {
                this["ID_16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamBrowLForm,-1,1")]
        public string ID_17 {
            get {
                return ((string)(this["ID_17"]));
            }
            set {
                this["ID_17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamBrowRForm,-1,1")]
        public string ID_18 {
            get {
                return ((string)(this["ID_18"]));
            }
            set {
                this["ID_18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamMouthForm,-1,1")]
        public string ID_19 {
            get {
                return ((string)(this["ID_19"]));
            }
            set {
                this["ID_19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamMouthOpenY,0,1")]
        public string ID_20 {
            get {
                return ((string)(this["ID_20"]));
            }
            set {
                this["ID_20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamCheek,0,1")]
        public string ID_21 {
            get {
                return ((string)(this["ID_21"]));
            }
            set {
                this["ID_21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamBodyAngleX,-10,10")]
        public string ID_22 {
            get {
                return ((string)(this["ID_22"]));
            }
            set {
                this["ID_22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamBodyAngleY,-10,10")]
        public string ID_23 {
            get {
                return ((string)(this["ID_23"]));
            }
            set {
                this["ID_23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamBodyAngleZ,-10,10")]
        public string ID_24 {
            get {
                return ((string)(this["ID_24"]));
            }
            set {
                this["ID_24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamBreath,0,1")]
        public string ID_25 {
            get {
                return ((string)(this["ID_25"]));
            }
            set {
                this["ID_25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamArmLA,-10,10")]
        public string ID_26 {
            get {
                return ((string)(this["ID_26"]));
            }
            set {
                this["ID_26"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamArmRA,-10,10")]
        public string ID_27 {
            get {
                return ((string)(this["ID_27"]));
            }
            set {
                this["ID_27"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamArmLB,-10,10")]
        public string ID_28 {
            get {
                return ((string)(this["ID_28"]));
            }
            set {
                this["ID_28"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamArmRB,-10,10")]
        public string ID_29 {
            get {
                return ((string)(this["ID_29"]));
            }
            set {
                this["ID_29"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamHandL,-1,1")]
        public string ID_30 {
            get {
                return ((string)(this["ID_30"]));
            }
            set {
                this["ID_30"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamHandR,-1,1")]
        public string ID_31 {
            get {
                return ((string)(this["ID_31"]));
            }
            set {
                this["ID_31"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamHairFront,-1,1")]
        public string ID_32 {
            get {
                return ((string)(this["ID_32"]));
            }
            set {
                this["ID_32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamHairSide,-1,1")]
        public string ID_33 {
            get {
                return ((string)(this["ID_33"]));
            }
            set {
                this["ID_33"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamHairBack,-1,1")]
        public string ID_34 {
            get {
                return ((string)(this["ID_34"]));
            }
            set {
                this["ID_34"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamHairFluffy,0,1")]
        public string ID_35 {
            get {
                return ((string)(this["ID_35"]));
            }
            set {
                this["ID_35"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamShoulderY,0,10")]
        public string ID_36 {
            get {
                return ((string)(this["ID_36"]));
            }
            set {
                this["ID_36"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamBustX,-1,1")]
        public string ID_37 {
            get {
                return ((string)(this["ID_37"]));
            }
            set {
                this["ID_37"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamBustY,-1,1")]
        public string ID_38 {
            get {
                return ((string)(this["ID_38"]));
            }
            set {
                this["ID_38"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamBaseX,-10,10")]
        public string ID_39 {
            get {
                return ((string)(this["ID_39"]));
            }
            set {
                this["ID_39"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ParamBaseY,-10,10")]
        public string ID_40 {
            get {
                return ((string)(this["ID_40"]));
            }
            set {
                this["ID_40"] = value;
            }
        }
    }
}
